CREATE DATABASE `mahook`;

USE `mahook`;

CREATE TABLE IF NOT EXISTS webhooks (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `channelID` VARCHAR(20) NOT NULL,
    `webhookToken` VARCHAR(200) NOT NULL,
    `options` TINYINT UNSINGED,
    `roleID` VARCHAR(20),
);

CREATE TABLE IF NOT EXISTS notices (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `date` DATETIME NOT NULL,
    `title` TEXT,
    `content` TEXT
);

CREATE TABLE IF NOT EXISTS lastTweet (
    `key_str` VARCHAR(10) NOT NULL UNIQUE,
    `id` BIGINT UNSIGNED NOT NULL
);

GRANT ALL ON `mahook`.* TO 'mahook-db'@'%';
