name: auto deploy production
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and Release
        run: |
          docker build -t ${{secrets.DOCKERHUB_REPO_PROD}} .
          docker tag ${{secrets.DOCKERHUB_REPO_PROD}}:latest ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_PROD}}:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_PROD}}:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker rm -f $(docker ps -aqf "name=^${{secrets.DOCKERHUB_REPO_PROD}}")
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_PROD}}:latest
            sudo docker run -d -p 3003:3000 --env-file /home/bass9030/mahook.env --name ${{secrets.DOCKERHUB_REPO_PROD}} ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_PROD}}:latest
            sudo docker image prune -f
