name: auto deploy debug
on:
  push:
    branches:
      - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Release
        run: |
          docker build -t mahook-dev -f dockerfile.dev .
          docker image save mahook-dev:latest -o ./mahook-dev.tar
          chmod 664 ./mahook-dev.tar
      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2234
          source: "./mahook-dev.tar"
          target: "/home/bass9030"
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2234
          script: |
            docker rm -f $(docker ps -aqf "name=^mahook-dev")
            docker load --input /home/bass9030/mahook-dev.tar
            docker run -d -p 9999:3000 --env-file /home/bass9030/mahook.dev.env --name mahook-dev --restart always mahook-dev:latest
            docker image prune -f
            rm /home/bass9030/mahook-dev.tar
