name: auto deploy debug
on:
    push:
        branches:
            - debug
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
            tags:
                description: "Test scenario tags"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  docker build -t mahook-web-dev -f dockerfile .
                  docker build -t mahook-db-dev -f dockerfile.mariadb .
                  docker image save mahook-web-dev:latest -o ./mahook-web-dev.tar
                  docker image save mahook-db-dev:latest -o ./mahook-db-dev.tar
                  chmod 664 ./mahook-web-dev.tar
                  chmod 664 ./mahook-db-dev.tar
            - name: Deploy web server image
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 2234
                  source: "./mahook-web-dev.tar"
                  target: "/home/bass9030"
            - name: Deploy db image
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 2234
                  source: "./mahook-db-dev.tar"
                  target: "/home/bass9030"
            - name: Restarting service
              uses: appleboy/ssh-action@master
              id: deploy
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 2234
                  script: |
                      docker-compose -f docker-compose-dev.yaml down
                      docker rmi -f $(docker images -aq "mahook-*-dev")
                      docker load --input /home/bass9030/mahook-web-dev.tar
                      docker load --input /home/bass9030/mahook-db-dev.tar
                      docker-compose -f docker-compose-dev.yaml --env-file /home/bass9030/mahook.dev.env up -d
                      rm /home/bass9030/mahook-*-dev.tar
